root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/kojo"
  cmd = "go build -o ./tmp/kojo ./cmd/kojo"
  delay = 500
  exclude_dir = ["tmp", "web", "vendor", ".git"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = 500
  send_interrupt = true
  stop_on_error = true

[log]
  main_only = true
